image:
  name: zfmaster/deployment:7.0.2
  username: $DOCKER_USERNAME
  password: $DOCKER_PASSWORD
  email: $DOCKER_EMAIL

pipelines:
  tags:
    '*':
      - step:
          script:
            - dep deploy demelectric.molbak.at -o target=$BITBUCKET_TAG




