image:
  name: zfmaster/deployment:7.0.2
  username: $DOCKER_USERNAME
  password: $DOCKER_PASSWORD
  email: $DOCKER_EMAIL

pipelines:
  tags:
    '*':
      - parallel:
          steps:
            - step:
                script:
                  - dep deploy demelectric.molbak.at -o target=$BITBUCKET_TAG -o writable_dirs=''
            - step:
                script:
                  - dep deploy dev.demelectric.ch -o target=$BITBUCKET_TAG -o bin/php=/opt/plesk/php/7.4/bin/php -o http_group=psacln
    '*-RC*':
      - step:
          script:
            - dep deploy stage.demelectric.ch -o target=$BITBUCKET_TAG -o bin/php=/opt/plesk/php/7.4/bin/php -o http_group=psacln




